# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160420_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.IntegerField()),
                ('date_month', models.IntegerField()),
                ('date_day', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='pub_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='date_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Date'),
        ),
    ]
