# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160424_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_year',
            field=models.CharField(max_length=4),
        ),
    ]
